services:
  - type: web
    runtime: node
    name: watch-hr-backend
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    autoDeploy: true

  - type: static
    name: map-task-frontend
    rootDir: map-task-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_WS_URL
        value: wss://watch-hr-backend.onrender.com
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
    headers:
      - path: "/*"
        name: X-Content-Type-Options
        value: nosniff
