services:
  - type: web
    runtime: node
    name: watch-hr-backend
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    autoDeploy: true

  - type: web
    runtime: node
    name: watch-hr-backend-matcher
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    autoDeploy: true

  - type: web
    runtime: node
    name: map-task-frontend
    plan: free
    rootDir: map-task-frontend
    buildCommand: npm install && npm run build && npm install -g serve
    startCommand: serve dist -s -l $PORT
    envVars:
      - key: VITE_WS_URL
        value: wss://watch-hr-backend-u96c.onrender.com
      - key: VITE_WS_URL_DIRECTOR
        value: wss://watch-hr-backend-u96c.onrender.com
      - key: VITE_WS_URL_MATCHER
        value: wss://watch-hr-backend-matcher-u96c.onrender.com
    autoDeploy: true
